Application:
  Capabilities:
    V2_0: true
  Organizations: null
  Policies:
    Admins:
      Rule: MAJORITY Admins
      Type: ImplicitMeta
    Endorsement:
      Rule: MAJORITY Endorsement
      Type: ImplicitMeta
    LifecycleEndorsement:
      Rule: MAJORITY Endorsement
      Type: ImplicitMeta
    Readers:
      Rule: ANY Readers
      Type: ImplicitMeta
    Writers:
      Rule: ANY Writers
      Type: ImplicitMeta
Capabilities:
  Application:
    V2_0: true
  Channel:
    V2_0: true
  Orderer:
    V2_0: true
Channel:
  Capabilities:
    V2_0: true
  Policies:
    Admins:
      Rule: MAJORITY Admins
      Type: ImplicitMeta
    Readers:
      Rule: ANY Readers
      Type: ImplicitMeta
    Writers:
      Rule: ANY Writers
      Type: ImplicitMeta
Orderer:
  Addresses:
  - orderer.digiblocks.com:7050
  BatchSize:
    AbsoluteMaxBytes: 99 MB
    MaxMessageCount: 10
    PreferredMaxBytes: 512 KB
  BatchTimeout: 2s
  EtcdRaft:
    Consenters:
    - ClientTLSCert: crypto-config/ordererOrganizations/2/orderers/orderer.orderer.2/tls/server.crt
      Host: orderer.2
      Port: 7050
      ServerTLSCert: crypto-config/ordererOrganizations/[0]/orderers/orderer.2/tls/server.crt
  OrdererType: etcdraft
  Organizations: null
  Policies:
    Admins:
      Rule: MAJORITY Admins
      Type: ImplicitMeta
    BlockValidation:
      Rule: ANY Writers
      Type: ImplicitMeta
    Readers:
      Rule: ANY Readers
      Type: ImplicitMeta
    Writers:
      Rule: ANY Writers
      Type: ImplicitMeta
Organizations:
- ID: OrdererMSP
  MSPDir: crypto-config/ordererOrganizations/2/msp
  Name: OrdererOrg
  Policies:
    Admins:
      Rule: OR('OrdererMSP.admin')
      Type: Signature
    Readers:
      Rule: OR('OrdererMSP.member')
      Type: Signature
    Writers:
      Rule: OR('OrdererMSP.member')
      Type: Signature
- &id001
  AnchorPeers:
  - Host: peer0.org0.2
    Port: 10051
  ID: peer0.org0.2
  MSPDir: crypto-config/peerOrganizations/peer0.org0.2/msp
  Name: Org1MPS
  Policies:
    Admins:
      Rule: OR('Org1MPS.admin')
      Type: Signature
    Endorsement:
      Rule: OR('Org1MPS.peer')
      Type: Signature
    Readers:
      Rule: OR('Org1MPS.admin', 'Org1MPS.peer', 'Org1MPS.client')
      Type: Signature
    Writers:
      Rule: OR('Org1MPS.admin', 'Org1MPS.client')
      Type: Signature
Profiles:
  BasicChannel:
    Application:
      Capabilities:
        V2_0: true
      Organizations:
      - *id001
      Policies:
        Admins:
          Rule: MAJORITY Admins
          Type: ImplicitMeta
        Endorsement:
          Rule: MAJORITY Endorsement
          Type: ImplicitMeta
        LifecycleEndorsement:
          Rule: MAJORITY Endorsement
          Type: ImplicitMeta
        Readers:
          Rule: ANY Readers
          Type: ImplicitMeta
        Writers:
          Rule: ANY Writers
          Type: ImplicitMeta
    Capabilities:
      V2_0: true
    Consortium: SampleConsortium
    Policies:
      Admins:
        Rule: MAJORITY Admins
        Type: ImplicitMeta
      Readers:
        Rule: ANY Readers
        Type: ImplicitMeta
      Writers:
        Rule: ANY Writers
        Type: ImplicitMeta
  OrdererGenesis:
    Capabilities:
      V2_0: true
    Consortiums:
      SampleConsortium:
        Organizations:
        - AnchorPeers:
          - Host: peer0.org1.digiblocks.com
            Port: 7051
          ID: Org1MSP
          MSPDir: crypto-config/peerOrganizations/org1.digiblocks.com/msp
          Name: Org1MSP
          Policies:
            Admins:
              Rule: OR('Org1MSP.admin')
              Type: Signature
            Endorsement:
              Rule: OR('Org1MSP.peer')
              Type: Signature
            Readers:
              Rule: OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')
              Type: Signature
            Writers:
              Rule: OR('Org1MSP.admin', 'Org1MSP.client')
              Type: Signature
        - AnchorPeers:
          - Host: peer0.org2.digiblocks.com
            Port: 9051
          ID: Org2MSP
          MSPDir: crypto-config/peerOrganizations/org2.digiblocks.com/msp
          Name: Org2MSP
          Policies:
            Admins:
              Rule: OR('Org2MSP.admin')
              Type: Signature
            Endorsement:
              Rule: OR('Org2MSP.peer')
              Type: Signature
            Readers:
              Rule: OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')
              Type: Signature
            Writers:
              Rule: OR('Org2MSP.admin', 'Org2MSP.client')
              Type: Signature
    Orderer: []
    Policies:
      Admins:
        Rule: MAJORITY Admins
        Type: ImplicitMeta
      Readers:
        Rule: ANY Readers
        Type: ImplicitMeta
      Writers:
        Rule: ANY Writers
        Type: ImplicitMeta
